version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: lab11-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: labpass
      MYSQL_DATABASE: lab11db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3311:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-plabpass"]
      interval: 5s
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: lab11-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: labpass
    ports:
      - "8082:80"
    depends_on:
      - db

  app:
    build: .
    container_name: lab11-app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: labpass
      DB_NAME: lab11db
      DB_PORT: 3306
      PORT: 5000
    ports:
      - "5011:5000"

volumes:
  dbdata:
